//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dell.CTO.Enstratius.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.enstratius.com:15000")]
        public string host_name {
            get {
                return ((string)(this["host_name"]));
            }
            set {
                this["host_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HUFVVXTGJWVZYFWRMAHU")]
        public string api_access_id {
            get {
                return ((string)(this["api_access_id"]));
            }
            set {
                this["api_access_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test")]
        public string user_agent {
            get {
                return ((string)(this["user_agent"]));
            }
            set {
                this["user_agent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/enstratus/2013-03-13")]
        public string api_root {
            get {
                return ((string)(this["api_root"]));
            }
            set {
                this["api_root"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("you must set an environment variable called ES_SECRET_KEY. Do not change this val" +
            "ue. It is for information only")]
        public string api_secret_key {
            get {
                return ((string)(this["api_secret_key"]));
            }
            set {
                this["api_secret_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<addDeployment>
  <deployment budget=""{budget}"" type=""{deployment_type}"" >
    <name>{name}</name>
	<description>{description}</description>
	<label>{label}</label>
	<forServiceCatalog>{for_service_catalog}</forServiceCatalog>
	<drStorageRegion regionId=""{storage_region_id}"" />
	<backupWindow>
	 <timeWindow daysOfWeek=""{backup_days_of_week}"" startHour=""{backup_start_hour}"" startMinute=""{backup_start_minute}"" endHour=""{backup_end_hour}"" endMinute=""{backup_end_minute}"" />
	</backupWindow>
	<maintenanceWindow>
	 <timeWindow daysOfWeek=""{maintenance_days_of_week}"" startHour=""{maintenance_start_hour}"" startMinute=""{maintenance_start_minute}"" endHour=""{maintenance_end_hour}"" endMinute=""{maintenance_end_minute}"" />
	</maintenanceWindow>
  </deployment>
</addDeployment>")]
        public string deployment_xml {
            get {
                return ((string)(this["deployment_xml"]));
            }
            set {
                this["deployment_xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<deploy>\r\n  <deployment  />\r\n</deploy>")]
        public string launch_deployment_xml {
            get {
                return ((string)(this["launch_deployment_xml"]));
            }
            set {
                this["launch_deployment_xml"] = value;
            }
        }
    }
}
